### ISSUE TITLE
Node.js error

### ISSUE THREAD

**Issue by Jourday** [kelseyhightower/nocode#294]
Tried everything...

`node nothing.js` 

gives me:

`node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'nothing'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/home/dave/src/server/app.js:2:12)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Array.0 (module.js:470:10)`

**Comment by pablocarreraest** [comment]
you get it all wrong
try for run it: 
````
      
````
the project should take care of dependecies
