### ISSUE TITLE
AndroidRuntime(342): Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by maikotrindade** [kelseyhightower/nocode#5015]
Ran the code on Android Studio and got this error: 

```
04-08 10:27:56.763: E/AndroidRuntime(342): FATAL EXCEPTION: main
04-08 10:27:56.763: E/AndroidRuntime(342): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.tourinfo/com.example.tourinfo.MainActivity}: java.lang.NullPointerException
04-08 10:27:56.763: E/AndroidRuntime(342):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1647)
04-08 10:27:56.763: E/AndroidRuntime(342):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
04-08 10:27:56.763: E/AndroidRuntime(342):  at android.app.ActivityThread.access$1500(ActivityThread.java:117)
04-08 10:27:56.763: E/AndroidRuntime(342):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
04-08 10:27:56.763: E/AndroidRuntime(342):  at android.os.Handler.dispatchMessage(Handler.java:99)
04-08 10:27:56.763: E/AndroidRuntime(342):  at android.os.Looper.loop(Looper.java:123)
04-08 10:27:56.763: E/AndroidRuntime(342):  at android.app.ActivityThread.main(ActivityThread.java:3683)
04-08 10:27:56.763: E/AndroidRuntime(342):  at java.lang.reflect.Method.invokeNative(Native Method)
04-08 10:27:56.763: E/AndroidRuntime(342):  at java.lang.reflect.Method.invoke(Method.java:507)
04-08 10:27:56.763: E/AndroidRuntime(342):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
04-08 10:27:56.763: E/AndroidRuntime(342):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
04-08 10:27:56.763: E/AndroidRuntime(342):  at dalvik.system.NativeStart.main(Native Method)
04-08 10:27:56.763: E/AndroidRuntime(342): Caused by: java.lang.NullPointerException
04-08 10:27:56.763: E/AndroidRuntime(342):  at com.example.tourinfo.MainActivity.onCreate(MainActivity.java:37)
04-08 10:27:56.763: E/AndroidRuntime(342):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
04-08 10:27:56.763: E/AndroidRuntime(342):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
04-08 10:27:56.763: E/AndroidRuntime(342):  ... 11 more
```

What should I do?

**Comment by AraujoJordan** [comment]
Replace `java`/`kotlin` with `nocode`

**Comment by maikotrindade** [comment]
<img width="252" alt="Screen Shot 2023-01-05 at 22 36 59" src="https://user-images.githubusercontent.com/3600906/210911978-19385081-e9b5-4634-8665-3ae67870fa23.png">

It worked @AraujoJordan 🥳 Thank you!
